### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hariprakashr** [chrisvfritz/vue-2.0-simple-routing-example#1] opened 2016-09-20 02:55 UTC
I set up the local instance as mentioned in the doc. But its not working at all. It doesn't through up any error in the console as well.

**Comment by chrisvfritz** [comment] 2016-09-20 04:53
Fixed now. It was a module importing issue, due to a change in either Babel or Webpack. Still hunting down the root cause.

**Closed as completed by chrisvfritz** 2016-09-20 04:53 UTC
